version: '3'
services:
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - /pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports: 
      - 8080:8080
    volumes:
     - .:/code
    environment:
      POSTGRES_DB: 'chat'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_HOST: 'db'
    depends_on:
      - db
