name: Java CI

on:
  pull_request:
    branches:
    - master
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven jdbc
      run: mvn -B package --file backend/pom.xml -D active.profile=jdbc
    - name: Build with Maven orm
      run: mvn -B package --file backend/pom.xml -D active.profile=orm
